// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WerewolfParty_Server.DbContext;

#nullable disable

namespace WerewolfParty_Server.Migrations
{
    [DbContext(typeof(WerewolfDbContext))]
    partial class WerewolfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WerewolfParty_Server.Entities.PlayerRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAlive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_alive");

                    b.Property<int>("NightKilled")
                        .HasColumnType("integer")
                        .HasColumnName("night_killed");

                    b.Property<int>("PlayerRoomId")
                        .HasColumnType("integer")
                        .HasColumnName("player_room_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("game_role");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerRoomId")
                        .IsUnique();

                    b.ToTable("player_role");
                });

            modelBuilder.Entity("WerewolfParty_Server.Entities.PlayerRoomEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvatarIndex")
                        .HasColumnType("integer")
                        .HasColumnName("avatar_index");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nickname");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("room_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("player_status");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("player_room");
                });

            modelBuilder.Entity("WerewolfParty_Server.Entities.PushSubscriptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<DateTime>("LastSeenDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_date");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p256dh");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("PlayerId");

                    b.ToTable("push_subscription");
                });

            modelBuilder.Entity("WerewolfParty_Server.Entities.RoomEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int?>("CurrentModeratorId")
                        .HasColumnType("integer")
                        .HasColumnName("current_moderator");

                    b.Property<int>("CurrentNight")
                        .HasColumnType("integer")
                        .HasColumnName("current_night");

                    b.Property<int>("GameState")
                        .HasColumnType("integer")
                        .HasColumnName("game_state");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<bool>("ModeratorBadgeAssigned")
                        .HasColumnType("boolean")
                        .HasColumnName("moderator_badge_assigned");

                    b.Property<int?>("NightStep")
                        .HasColumnType("integer")
                        .HasColumnName("night_step");

                    b.Property<DateTime?>("NightStepDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("night_step_deadline");

                    b.Property<int>("WinCondition")
                        .HasColumnType("integer")
                        .HasColumnName("win_condition");

                    b.Property<bool>("isDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_day");

                    b.HasKey("Id");

                    b.HasIndex("CurrentModeratorId");

                    b.ToTable("room");
                });

            modelBuilder.Entity("WerewolfParty_Server.Entities.RoomGameActionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<int>("AffectedPlayerRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("affected_player_role_id");

                    b.Property<int>("Night")
                        .HasColumnType("integer")
                        .HasColumnName("night");

                    b.Property<int?>("PlayerRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("player_role_id");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("action_state");

                    b.HasKey("Id");

                    b.HasIndex("AffectedPlayerRoleId");

                    b.HasIndex("PlayerRoleId");

                    b.HasIndex("RoomId");

                    b.ToTable("room_game_action");
                });

            modelBuilder.Entity("WerewolfParty_Server.Entities.RoomSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowMultipleSelfHeals")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_multiple_self_heals");

                    b.Property<int>("NightStepSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(45)
                        .HasColumnName("night_step_seconds");

                    b.Property<int>("NumberOfWerewolves")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_werewolves");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("room_id");

                    b.PrimitiveCollection<int[]>("SelectedRoles")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("selected_roles");

                    b.Property<bool>("SelfModerated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("self_moderated");

                    b.Property<bool>("ShowGameSummary")
                        .HasColumnType("boolean")
                        .HasColumnName("show_game_summary");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("role_settings");
                });

            modelBuilder.Entity("WerewolfParty_Server.Entities.PlayerRoleEntity", b =>
                {
                    b.HasOne("WerewolfParty_Server.Entities.PlayerRoomEntity", "PlayerRoom")
                        .WithOne("PlayerRole")
                        .HasForeignKey("WerewolfParty_Server.Entities.PlayerRoleEntity", "PlayerRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerRoom");
                });

            modelBuilder.Entity("WerewolfParty_Server.Entities.PlayerRoomEntity", b =>
                {
                    b.HasOne("WerewolfParty_Server.Entities.RoomEntity", "Room")
                        .WithMany("PlayersInRoom")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("WerewolfParty_Server.Entities.RoomEntity", b =>
                {
                    b.HasOne("WerewolfParty_Server.Entities.PlayerRoomEntity", "CurrentModerator")
                        .WithMany()
                        .HasForeignKey("CurrentModeratorId");

                    b.Navigation("CurrentModerator");
                });

            modelBuilder.Entity("WerewolfParty_Server.Entities.RoomGameActionEntity", b =>
                {
                    b.HasOne("WerewolfParty_Server.Entities.PlayerRoleEntity", "AffectedPlayerRole")
                        .WithMany()
                        .HasForeignKey("AffectedPlayerRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WerewolfParty_Server.Entities.PlayerRoleEntity", "PlayerRole")
                        .WithMany()
                        .HasForeignKey("PlayerRoleId");

                    b.HasOne("WerewolfParty_Server.Entities.RoomEntity", "Room")
                        .WithMany("GameActions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffectedPlayerRole");

                    b.Navigation("PlayerRole");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("WerewolfParty_Server.Entities.RoomSettingsEntity", b =>
                {
                    b.HasOne("WerewolfParty_Server.Entities.RoomEntity", "Room")
                        .WithOne("RoleSettings")
                        .HasForeignKey("WerewolfParty_Server.Entities.RoomSettingsEntity", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("WerewolfParty_Server.Entities.PlayerRoomEntity", b =>
                {
                    b.Navigation("PlayerRole");
                });

            modelBuilder.Entity("WerewolfParty_Server.Entities.RoomEntity", b =>
                {
                    b.Navigation("GameActions");

                    b.Navigation("PlayersInRoom");

                    b.Navigation("RoleSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
